---
abstract: 'Implements an uri_for_static method for Catalyst applications!'
author:
  - 'Matthias Dietrich <perl@rainboxx.de>'
build_requires:
  Catalyst: 5.80029
  Moose: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-UriForStatic
provides:
  CatalystX::UriForStatic:
    file: lib/CatalystX/UriForStatic.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/rainboxx/CatalystX-UriForStatic/
version: 0.01
